### ISSUE TITLE
librdkafka 1.1.0

### ISSUE THREAD

**Issue by GeorgeShagov** [plicease/Alien-Librdkafka#4]
The latest release for librdkafka is 1.1.0
Yet when I tried to install `sudo cpanm    --reinstall --force Kafka::Librd`
I see that librdkafka is 0.11.6
Is there any way to specify the version of librdkafka?
thx

**Comment by GeorgeShagov** [comment]
```
    alien_repository => {
        protocol => 'https',
        exact_filename => 'https://github.com/edenhill/librdkafka/archive/v0.11.6.tar.gz',
        exact_version => 'v0.11.6',
    },
```

**Comment by GeorgeShagov** [comment]
here is the latest:
`https://github.com/edenhill/librdkafka/archive/v1.1.0.zip`

**Comment by GeorgeShagov** [comment]
https://github.com/plicease/Alien-Librdkafka/pull/5

**Comment by GeorgeShagov** [comment]
changed to tbz

**Comment by plicease** [comment]
You can use the environment to override the repo values:

https://metacpan.org/pod/Alien::Base::ModuleBuild#ALIEN_${MODULENAME}_REPO_${PROTOCOL}_${KEY}

You can also install librdkafka manually and add the `lib/pkgconf` directory to `PKG_CONFIG_PATH`.  That would use it as a system library.

**Comment by plicease** [comment]
#8 should address this

**Comment by GeorgeShagov** [comment]
Hello
had this update been deployed to cpan I wonder, I tried to rebuild from cpan, and still see:
`#define RD_KAFKA_VERSION  0x000b06ff`
thx in advance

**Comment by plicease** [comment]
Is that for a `system` or `share` install? This is what I see for a share install:

```
veracious% cd `perl -MAlien::Librdkafka -E 'say Alien::Librdkafka->dist_dir'`/include
Use of uninitialized value $1 in concatenation (.) or string at /home/ollisg/perl5/lib/perl5/Alien/Base.pm line 285.
Use of uninitialized value $1 in concatenation (.) or string at /home/ollisg/perl5/lib/perl5/Alien/Base.pm line 285.
Could not resolve -lstdc++ at -e line 0.
veracious% grep RD_KAFKA_VERSION librdkafka/*.h
librdkafka/rdkafka.h:#define RD_KAFKA_VERSION  0x010100ff
librdkafka/rdkafka.h: * @sa See RD_KAFKA_VERSION for how to parse the integer format.
librdkafka/rdkafkacpp.h:#define RD_KAFKA_VERSION  0x010100ff
librdkafka/rdkafkacpp.h: * @sa See RD_KAFKA_VERSION for how to parse the integer format.
```
